### PR TITLE
Support for placeholder translations

### PR DESCRIPTION
**Pull request by ghost**
Look for the placeholder-attribute, and if present, try to find a translation.

### CODE REVIEW

**Comment by bartekn** [comment]
@LarsDR I'm no longer maintaining this package. Do you want to become a collaborator?

**Comment by ghost** [comment]
Hi @bartekn!

Sure thing. I've already made some more changes that allows for more flexible use :-)

**Comment by bartekn** [comment]
Invite sent!

**Comment by bartekn** [comment]
You can also send me your `npm` username and I'll add you as a co-owner.

**Comment by ghost** [comment]
Just created an account. Username is "larsdr" :-)

**Comment by bartekn** [comment]
> Just created an account. Username is "larsdr" :-)

Added you: https://www.npmjs.com/package/gulp-angular-gettext-export-html

**Pull request closed without merging**
